### PR TITLE
Flask server homepage routing

### PR DESCRIPTION
**Pull request by NicholasKobald**
This PR sets up the bare bones flask server that will handle the back end for our eventual app.

To insure we won't run in to more complicated issues down the line, could everyone try to get this running on their machine?

- [x] checkout this branch
- [x] make a new virtualennvironment for this project. Let me know if you need help with this, most likely if you are on OSX or Linux `mkvirtualenv -p python3 onc` (onc being the name of the environment) will work 
- [x] `pip install -r requirements` 
- [x] Then running `python app.py` produces the following, correct output:
image
- [x] Visting the url shows:
image

@mattpaletta let me know if you see this leading to any issues

This sets us up for the next steps which are connecting this to a db, and adding the client side components to run our javascript (I'm thinking probably d3 is a good choice for us...)

### CODE REVIEW

**Comment by NicholasKobald** [comment]
Thanks! did that actually break things when you ran it?

**Comment by mattpaletta** [comment]
Yes, Pip didn't know how to install it.  Also, for mac users.  You have to sudo install `itsdangerous==0.24`, even though it's in a virtual environment :(

**Comment by NicholasKobald** [comment]
Weird, I didn't have to but its possible it went into site packages or something for me.

For the next person to try this, if you run into Mathews issue maybe try:

`pip install --upgrade -r requirements.txt`

**Comment by kmvg** [comment]
Works for me! Sorry for the delay on my end! Nice work!

**Comment by NicholasKobald** [comment]
@mattpaletta please merge if you are satisfied! I'll hold of since it still says requested changes

**Pull request merged**
